# Generated by Django 2.0.7 on 2019-06-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sand', '0002_auto_20190602_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupghost',
            name='element',
        ),
    ]
