# Generated by Django 2.0.7 on 2019-06-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sand', '0009_groupghost_element'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupghost',
            name='element',
        ),
    ]
