# Generated by Django 2.0.7 on 2019-06-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sand', '0012_auto_20190602_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupghost',
            name='element',
        ),
    ]
