# Generated by Django 2.0.7 on 2019-06-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sand', '0013_remove_groupghost_element'),
    ]

    operations = [
    ]
