# Generated by Django 2.0.7 on 2019-06-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sand', '0014_auto_20190602_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupghost',
            name='element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sand.GroupElements'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vampire',
            name='health',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
